#Common
label: gitops

#Deployment
replicas: 3
image:
  repository: asia.gcr.io/robotic-charmer-371101/china_gcp_learning # 変更箇所 DOCKERHUB_REPO_NAME
  tag: d207fa4bcdfc5a8f3862a4fe6f1c088053759891

imageConfig:
  pullPolicy: IfNotPresent

#Service
service_type: LoadBalancer